project_id = "ijnwvbdazdowiljfcmpq"

[functions.ai-chat]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.transcribe-google]
verify_jwt = false

[functions.gemini-tts]
verify_jwt = false

[functions.creator-ai]
verify_jwt = false

[functions.novel-translate]
verify_jwt = false

[functions.video-recap]
verify_jwt = false

[functions.admin-register]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.transformative-transcribe]
verify_jwt = false

[functions.transformative-translate]
verify_jwt = false
 
 [functions.admin-2fa]
 verify_jwt = false

[functions.recap-script-generator]
verify_jwt = false

[functions.promotion-tracking]
verify_jwt = false

[functions.get-upload-url]
verify_jwt = false

[functions.upload-chunk]
verify_jwt = false
